### ISSUE TITLE
Rodadas não somou o CF ao último valor de FLN simulado

### ISSUE THREAD

**Issue by LilianUhlmann** [RomuloPBenedetti/PhenoGlad#10]
* Fazendo algumas rodadas teste, percebi que o modelo não está simulando corretamento o FLN (Final Leaf Number) de algumas épocas. Não há uma explicação para que o erro esteja acontecendo, pois em alguns anos ele roda corretamente, somando o CF (Correction Factor) ao último valor de número de folhas e em outras épocas ele não soma. **O cálculo de número de folhas está correto, o que está rodando errado é que, algumas vezes, o modelo não soma o CF ao último valor de número de folhas simulado**.
   * Me parece que há uma maior frequência de erros nas simulações realizadas a partir da emergência do que do plantio.
   * Fiz algumas rodadas para diferentes anos e cultivares, a partir da emergência e a partir do plantio, e o **cálculo do DVS está correto**.

**Comment by RomuloPBenedetti** [comment]
Para que todos os envolvidos possam testar, por favor disponibilize o arquivo de entrada, e um exemplo de arquivo de resultado defeituoso, 
**É possível arrastar e soltar documentos nos comentários de issues do github**

**Comment by LilianUhlmann** [comment]
[Jester ep15 EM.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/50330/Jester.ep15.EM.txt)

[tempveg.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/50328/tempveg.txt)

*  Disponibilizei um exemplo de rodada em que o modelo não somou o CF ao último valor de FLN simulado. A rodada correponde à cultivar Jester, iniciando da emergência (dia 25, ano=4).

* O segundo arquivo corresponde aos dados meteorológicos de entrada.

**Comment by RomuloPBenedetti** [comment]
O problema está relacionado a [esta](https://github.com/RomuloPBenedetti/PhenoGlad/blob/master/PhenoGlad(Fortran)/src/Model.f90#L157-L177) é preciso avaliar se as condições dos IFs nesta parte do modelo estão sendo satisfeitas corretamente, a melhor abordagem posteriormente seria simplificar a dependência de variáveis por parte da lógica nessa parte do modelo.

Eu preciso saber qual é o resultado correto esperado também.
