### ISSUE TITLE
Coeficientes para cultivares Precoces, Intermediárias e Tardias (inserir no modelo Fortran)

### ISSUE THREAD

**Issue by LilianUhlmann** [RomuloPBenedetti/PhenoGlad#11]
* **Valores dos coeficientes para cultivares precoces, intermediárias e tardias (inserir no modelo Fortran)**

    * **Precoces:**
       * rmaxs = 0.0938
       * rmaxv = 0.0182
       * rmaxh = 0.0224
       * rmaxf = 0.0659

  * **Intermediária I:**
       * rmaxs = 0.0961
       * rmaxv = 0.0172
       * rmaxh = 0.0214
       * rmaxf = 0.0716

  * **Intermediária II:**
       * rmaxs = 0.0867
       * rmaxv = 0.0158
       * rmaxh = 0.0216
       * rmaxf = 0.0689

  * **Tardia:**
       * rmaxs = 0.0896
       * rmaxv = 0.0135
       * rmaxh = 0.0244
       * rmaxf = 0.0627

**Comment by RomuloPBenedetti** [comment]
ultima edição dos coeficientes realizada no commit 7a9c075.
