### ISSUE TITLE
Criar os elementos de tabela e gráficos na interface javaFX

### ISSUE THREAD

**Issue by RomuloPBenedetti** [RomuloPBenedetti/PhenoGlad#18]

**Comment by LilianUhlmann** [comment]
* **Modelo de saída dos resultados resumidos do modelo (informações gerais e tabela):**

 * Nome do local da simulação:
 * Início da simulação: (plantio ou emergência)
 * Data de início (dia do ano):
 * Cultivar:

Dados de fenologia:

Estágio|Data|Dia do ano|DAE ou DAP|Definição
|--------|-------|-------------|----------------|-----------|
VE| | | |Emergência |
|V1| | | |Primeira folha|
V2| | | |Segunda folha|
|V3| | | |Terceira folha|
|V4| | | |Quarta folha|
|V5| | | |Quinta folha|
|V6| | | |Sexta folha|
|V7| | | |Sétima folha|
|V8| | | |Oitava folha|
|Vn| | | |Enésima folha|
|VF| | | |Folha bandeira|
|R0| | | |Início do desenvolvimento da espiga floral no interior do cartucho|
|R1| | | |Espigamento|
|R2| | | |Ponto de colheita comercial. Desenvolvimento dos botões florais.|
|R3| | | |Início da antese|
|R3.4 / R3.5| | | |Metade da antese e início da senescência da haste floral|
|R3.6| | | |Metade da senescência da haste floral|
|R4| | | |Final da antese|
|R5| | | |Senescência completa da haste floral|

**Comment by LilianUhlmann** [comment]
* **English version:**

 * Site name:
 * Star from: (planting or emergence)
 * Start date (doy):
 * Cultivar:

Phenology:

Stage|Date|Doy|DAP or DAE|Definition
|-------|------|-----|---------------|-----------|
VE| | | |Emergence|
|V1| | | |First sheath|
V2| | | |Second sheath|
|V3| | | |Third sheath|
|V4| | | |Fourth sheath|
|V5| | | |Fifth sheath|
|V6| | | |Sixth sheath|
|V7| | | |Seventh sheath|
|V8| | | |Eighth sheath|
|Vn| | | |Nth leaf|
|VF| | | |Flag leaf|
|R0| | | |Florets differentiation starts at the apex|
|R1.0| | | |Heading|
|R2| | | |Commercial harvest point. Blooming.|
|R3| | | |Onset of anthesis|
|R3.4 / R3.5| | | |Half of anthesis and beginning floret senescence|
|R3.6| | | |Half of florets senesced|
|R4| | | |Anthesis completed|
|R5| | | |End of floret senescence|

**Comment by LilianUhlmann** [comment]
![grafico dados meteorologicos phenoglad](https://cloud.githubusercontent.com/assets/16117157/11920697/7f8e82e2-a75d-11e5-8f88-68e28cbb3135.png)

**Comment by LilianUhlmann** [comment]
* Evolução do desenvolvimento:
![grafico resultado dvs e v-stage](https://cloud.githubusercontent.com/assets/16117157/11961329/ee16f35e-a8be-11e5-9043-924c282a1b5f.png)

* OBS: no gráfico do desenvolvimento vão ser apresentadas as variáveis: DVS e V-Stage. Na parte superior do gráfico, deverá apacer uma apontamento de alguns estágios importantes, como R0, R1, R2 e R5, assim como aparece no resultado do SimulArroz:

![modelo simularroz](https://cloud.githubusercontent.com/assets/16117157/11961486/10785892-a8c0-11e5-84b4-df36ff580d36.png)

 * No gráfico de resposta do programa PhenoGlad, nas caixinhas para marcar ao lado deverá aparecer **DVS e V-stage.**

**Comment by LilianUhlmann** [comment]
* **Momento de ocorrência dos estágios de desenvolvimento no modelo PhenoGlad:**


Tabela:

Estágio|Data|Dia do ano|DAE ou DAP|Momento a ser considerado para ocorrência
|--------|-------|-------------|----------------|-----------|
VE| | | |Primeiro dia em que o DVS for igual ou maior a 0.0 |
|V1| | | |Primeiro dia em que a coluna do V_Stage é igual a 1.0|
V2| | | |Primeiro dia em que a coluna do V_Stage é igual a 2.0|
|V3| | | |Primeiro dia em que a coluna do V_Stage é igual a 3.0|
|V4| | | |Primeiro dia em que a coluna do V_Stage é igual a 4.0|
|V5| | | |Primeiro dia em que a coluna do V_Stage é igual a 5.0|
|V6| | | |Primeiro dia em que a coluna do V_Stage é igual a 6.0|
|V7| | | |Primeiro dia em que a coluna do V_Stage é igual a 7.0|
|V8| | | |Primeiro dia em que a coluna do V_Stage é igual a 8.0|
|VF| | | |Primeiro dia em que ocorre o aparecimento da última folha simulada pelo modelo (coluna do V_Stage, no lugar do VF deve aparecer V e número da última folha simulada pelo modelo|
|R0| | | |Primeiro dia em que a coluna do V_Stage é igual a 3.0|
|R1.0| | | |Primeiro dia em que o DVS for igual ou maior a 0.8|
|R2| | | |Primeiro dia em que o DVS for igual ou maior a 1.0|
|R3| | | |Primeiro dia em que o DVS for igual ou maior a 1.13|
|R3.4 / R3.5| | | |Primeiro dia em que o DVS for igual ou maior a 1.32|
|R3.6| | | |Primeiro dia em que o DVS for igual ou maior a 1.56|
|R4| | | |Primeiro dia em que o DVS for igual ou maior a 1.84|
|R5| | | |Primeiro dia em que o DVS for igual ou maior a 2.0|

**Comment by RomuloPBenedetti** [comment]
adicionar coluna a tabela com o valor do **v-stage**
