### ISSUE TITLE
Caso teste 1 - Teste da impressão dos estágios Vegetativos na tabela resumida

### ISSUE THREAD

**Issue by LilianUhlmann** [RomuloPBenedetti/PhenoGlad#22]
* **Resumo:** o caso teste consistiu na verificação se a tabela resumida está imprimindo corretamente os valores e a data de ocorrência dos estágios vegetativos, principalmente na parte do aparecimento das últimas folhas e da folha bandeira;

* **Pré-condições:** O modelo deve imprimir os estágios vegetativos até o aparecimento da **sexta folha (6°)** e depois imprimir a data de aparecimento da última folha (VF); é importante que, se não ocorrer a emissão de alguma folha na coluna do V_Stage (devido à soma do fator de correção), este valor não seja computado na tabela resumida.

* **Entradas:** A simulação foi realizada a partir do plantio, data de plantio: 01/11/2013, cultivar: Purple Flora;

* **Ação:** o usuário, para testar, deve optar pela simulação a partir do plantio, com data de plantio 01/11/2013, selecionar a cultivar Purple Flora, com os dados meteorológicos anexados abaixo (tempveg.txt);

* **Resultados obtidos:** 
   * Através da comparação dos dados impressos na tabela resumida da aba "resultados" do modelo com o arquivo de saída detalhado do modelo (result.txt), **na tabela detalhada** ocorreu a impressão correta da data de ocorrência dos estágios vegetativos até a 6° folha. Após isso, como o modelo somou o fator de correção aos dados de número de folhas, não ocorreu a emissão da 7° folha na coluna do V_Stage, pois houve a emissão da 8° folha direto. 

   * Devido a isso, na tabela resumida, houve a impressão da data de ocorrência da 7° e 8° folhas no mesmo dia (dia 359).

   * Então, para esta simulação ser impressa corretamente na tabela resumida dos resultados, deveria aparecer a data de emissão da 6° folha, não haveria emissão da 7° folha e após já ocorreria a emissão da folha bandeira (8° folha). 

   * Este resultado foi obtido pois esta cultivar é a que tem menor número de folhas.

   * Outro ponto observado foi que, como a simulação foi realizada a partir do plantio, na tabela resumida dos resultados na coluna que aparece "dias após a emergência" deveria ser impresso **"dias após o plantio"**, pois a simulação foi iniciada a partir do plantio.

   * Somente se a simulação iniciar a partir da emergência, a coluna deve ser **"dias após a emergência"**

* **Pós-condições:** Acredito que em várias vezes ocorrerá de não haver a emissão de alguma folha na coluna do V_Stage ao final do período de emissão de folhas, entre a 7° e a 12° folha. Ou seja, a emissão de alguma folhas não ocorrerá no final devido à soma do fator de correção. Ver se é possível implementar de algum estágio vegetativo não ser impresso se não ocorrer a emissão de alguma folha.

   * Os dados meteorológicos usados e a tabela detalhada dos resultados estão em anexo, bem como um print da tabela resumida da simulação.
![imagem1](https://cloud.githubusercontent.com/assets/16117157/12487376/0e898204-c04e-11e5-8aed-c8eaef75d605.jpg)
[result.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/99487/result.txt)
[tempveg.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/99488/tempveg.txt)

**Comment by RomuloPBenedetti** [comment]
This issue was moved to RomuloPBenedetti/CropModelsUFSM#6
