### ISSUE TITLE
Caso teste 2 - Temperatura letal superior atingida (acima de 48°C)

### ISSUE THREAD

**Issue by LilianUhlmann** [RomuloPBenedetti/PhenoGlad#23]
* **Resumo:** o caso teste consistiu na verificação dos resultados do modelo se a temperatura letal superior for atingida, ou seja, se a temperatura máxima for superior a 48°C. 

* **Pré-condições:** O modelo deve simular até o dia de ocorrência da temperatura letal superior e depois parar a simulação, pois a temperatura letal foi atingida pois, assim, a cultura é morta pelo calor.

* **Entradas:** A simulação foi realizada a partir do plantio, data de plantio: 15/01/2013, cultivar: Peter Pears;

* **Ação:** o usuário, para testar, deve optar pela simulação a partir do plantio, com data de plantio 15/01/2013, selecionar a cultivar Peter Pears, com os dados meteorológicos anexados abaixo (tempveg.txt);
   * OBS: Como para nossas condições não temos ocorrência de temperaturas máximas acima de 48°C, eu modifiquei o arquivo dos dados meteorológicos de entrada e inseri um valor de TMáx de 48.1°C no dia 40 para forçar o modelo a estas condições. 

* **Resultados obtidos:** 
   * Através da verificação dos dados impressos na tabela resumida da aba "resultados" do modelo, verifiquei que ocorreu a impressão correta da data de ocorrência dos estágios vegetativos até a 2° folha (no dia 36). 

   * Após isso, o modelo não simulou mais a partir do dia 40 pois ocorreu a morte da cultura pelo calor, pois neste dia ocorreu a temperatura máxima de 48,1°C. **OBS: Até aqui está tudo correto.**

   * Porém, na tabela resumida dos resultados apareceu a data de emissão do VF, ou folha bandeira. **Isto está incorreto**, pois como a simulação foi somente até V2 não ocorreu a emissão da folha bandeira da cultura.

   * Para estas condições de temperatura letal superior atingida, a emissão da folha bandeira só ocorreria se a ocorrência da temperatura letal de 48°C fosse atingida após a sua emissão, ou seja, após o primeiro dia em que o modelo simular a emissão da última folha.

* **Pós-condições**: na interface deveria aparecer um aviso com alerta de morte da cultura pela ocorrência de altas temperaturas, porém, esta condição não foi testada ainda pois não foi implementado na interface.

 * Segue o arquivo com dados meteorológicos de entrada (tempveg.txt), o arquivo com os resultados (result.txt) e um print da tabela com o resultado resumido.

[result.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/103227/result.txt)
[tempveg.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/103229/tempveg.txt)
![imagem temperatura 48 1](https://cloud.githubusercontent.com/assets/16117157/12551657/3ee28b0a-c353-11e5-82f2-f9ae6cb8e19d.jpg)

**Comment by RomuloPBenedetti** [comment]
This issue was moved to RomuloPBenedetti/CropModelsUFSM#5
