### ISSUE TITLE
Caso teste 3 - Impressão dos valores de dias após a emergência na tabela resumida

### ISSUE THREAD

**Issue by LilianUhlmann** [RomuloPBenedetti/PhenoGlad#24]
* **Resumo:** o caso teste consistiu na verificação se os dias após a emergência na tabela resumida estavam sendo impressos corretamente.

* **Pré-condições:** Na tabela resumida, os valores de dias após a emergência devem ser impressos corretamente, subtraindo o dia do ano de ocorrência dos estágios de desenvolvimento do dia do ano correspondente à emergência. .

* **Entradas:** A simulação foi realizada a partir da emergência, data de emergência: 10/10/2015, cultivar: Gold Field;

* **Ação:** o usuário, para testar, deve optar pela simulação a partir da emergência, com data de emergência 10/10/2015, selecionar a cultivar Gold Field, com os dados meteorológicos anexados abaixo (tempveg.txt);
  
* **Resultados obtidos:** 
   * Através da verificação dos dados impressos na tabela resumida da aba "resultados" do modelo, verifiquei que ocorreu a impressão correta dos dias após a emergência até o estágio VF, que foi 73 dias após a emergência.

   * Após isso, não ocorreu mais a impressão correta dos dias após a emergência, inclusive no dia simulado de R1 que foi no mesmo dia do VF, os dias após a emegência do R1 foram impressos incorretamente, ou seja, 73 DAE para VF e 74 DAE para R1, sendo que os dois estágios ocorreram no mesmo dia (22 de Dez. de 2015, dia do ano 356). Este erro de somar um dia a mais a partir do R1 persistiu até R5.
  
* **Pós-condições**: possibilidade de realizar uma nova simulação na tela inicial, o que já está ocorrendo de forma correta.

 * Segue o arquivo com dados meteorológicos de entrada (tempveg.txt), o arquivo com os resultados (result.txt) e um print da tabela com o resultado resumido.

[tempveg.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/105302/tempveg.txt)
[result.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/105303/result.txt)
![imagem dias apos a emergencia incorretos](https://cloud.githubusercontent.com/assets/16117157/12587762/cef1af5c-c43c-11e5-8a48-c552ed1c13a2.jpg)

**Comment by RomuloPBenedetti** [comment]
This issue was moved to RomuloPBenedetti/CropModelsUFSM#4
