### ISSUE TITLE
tarefas gerais para lançamento

### ISSUE THREAD

**Issue by RomuloPBenedetti** [RomuloPBenedetti/PhenoGlad#26]
- [x] simulações gerarem warnings 
 - [x] ler arquivo de entrada ao abrir (coldstart)
 - [x] ponto de colheita somente ate DVS = 1.05
 - [x] about e legenda
 - [x] alertas de interação (inserção de arquivo erro nos dados de entrada etc)
 - [x] ajuste de cor de menus
 - [x] sinalização de simulação realizada
 - [x] critério de v final não pode ser pegar o ultimo dia :
        se for encontrada condicao de morte da planta antes de encontrar o dia da ultima folha
        então não apresentar na tabela um vf (n existe folha final)
 - [x] manual
 - [x] ativar botoes de legenda
 - [x] 7 dias a mais linear no gráfico de linha
 - [x] estágios nos gráficos
 - [x]  na tabela quando dia de plantio, deve ser dias apos plantio
 - [x] tabela, mais uma coluna com n de folhas
 - [x] substituir menu por text-field no n de anos
 - [x] aumentar fonte alertas
 - [x] finalizar função de múltiplos anos

**Comment by LilianUhlmann** [comment]
* Detalhes que precisam ser ajustados:

- [ ] Se a simulação foi realizada até o ponto de colheita, na pasta files o arquivo resut.txt está imprimindo o resultado até o ciclo total, o correto seria aparecer somente até primeiro dia em que o DVS é maior ou igual a 1.0;

- [ ] Da mesma forma, quando a simulação for até o ponto de colheita, no gráfico dos resultados não presisa fazer a linha estabilizar por mais alguns dias, ela pode ir somente até o dia do ponto de colheita;

- [ ] Ajustar na parte do gráfico com os dados meteorológicos a palavra TMed, pois TMax está aparecendo 2x; nesta mesma parte, está faltando o último "e" da palavra "temperature";

- [ ] Na aba resultados --> Charts, substituir "evolution of development" por "progress of development";
