### ISSUE TITLE
Nomenclatura das simulações para que fiquem armazenadas

### ISSUE THREAD

**Issue by LilianUhlmann** [RomuloPBenedetti/PhenoGlad#27]
A nomeclatura das simulações deve ser feita da seguinte maneira:
 * **PL ou EM (data do plantio ou emergência)cultivar;R2 ou R5.**

Exemplo:
 * Para uma simulação realizada a partir do **plantio**, com data de plantio **30 de Setembro de 2013**, cultivar: **Purple Flora** até o **ponto de colheita**, o nome da pasta com esta simulação deve ser:
    * **PL(30-09-2013)Purple_Flora;R2**

 * Para uma simulação realizada a partir da **emergência**, com data de emergência **10 de Outubro de 2013**, cultivar: **Amsterda** até o **final do ciclo**, o nome da pasta com esta simulação deve ser:
    * **EM(10-10-2013)Amsterda;R5**

OBS: no caso de simulações com o simulador em inglês, o formato da data de plantio ou emergência deve ficar no formato MM/DD/AAAA, e no português DD/MM/AAAA.

**Comment by RomuloPBenedetti** [comment]
Foi adicionado ao fim o número de anos simulados
