### ISSUE TITLE
Alertas de validação de dados de entrada

### ISSUE THREAD

**Issue by RomuloPBenedetti** [RomuloPBenedetti/PhenoGlad#28]
**arquivo de entrada**

    * validar se tem o mesmo numero de elementos em cada linha 
    * validar os tipos de valores inteiro ou real
    * validar a sequencia de dias

**entradas do usuário**

    * alertar caso o o datepicker não valide a data
    * alertar quando a data esta fora do limite de dados
    * alertar quando o número de anos a simular for superior ao numero de anos disponível ou inferior a 
    * alertar quando uma cultivar não estiver selecionada

caso alguma destas falhas ocorra os arquivos não devem ser armazenados nem em results nem em files, a interface não deve reagir.

**Comment by LilianUhlmann** [comment]
**Validação dos alertas de erro da parte em inglês do modelo**:

**Comment by LilianUhlmann** [comment]
**Modificar alguns detalhes nos alertas de erro da versão em português**:

   1- **Key 80:** Foi encontrado: " _ " elementos incorretos na linha: " _ "

**Comment by LilianUhlmann** [comment]
**Validação dos alertas de erro da versão em inglês do programa:**

* O que acontece: Se o usuário coloca para simular duas safras, por exemplo, mas só tem dados meteorológicos para uma safra

* Foto de o alerta de dados meteorológicos faltantes não está aparecendo:
![imagem1](https://cloud.githubusercontent.com/assets/16117157/12827783/7d95b6c0-cb68-11e5-958e-c3563d223ace.jpg)

* O que se espera: Que a mensagem de erro "Insufficient meteorological data to run all years" apareça.

* Como reproduzir: usar os dados meteorológicos abaixo, com data de plantio: 30 de setembro de 2015 e simular para dois anos com qualquer cultivar.

[CasoTeste5.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/118142/CasoTeste5.txt)

**Comment by LilianUhlmann** [comment]
**Validação dos alertas de erro na versão em inglês do modelo:"

* O que está acontecendo: Este arquivo de dados meteorológicos está acusando erro quando teoricamente eu acredito que não tenha erro algum:

[tempveg (1).txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/118199/tempveg.1.txt)

**Comment by camilacbecker** [comment]
**Validação dos alertas de erro na versão em português do modelo**

- O que está acontecendo: este arquivo apresenta uma linha onde só consta o ano, pois eu exclui os dados do dia, da tmin e da tmax para fazer o teste, porém o modelo não acusa falha nos dados e realiza a rodada normalmente. A linha que foi apagada é bem no início do arquivo (dia 10 de 1963)

[dados sm força DANO.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/118393/dados.sm.forca.DANO.txt)

**Comment by LilianUhlmann** [comment]
* Neste comentário da Camila, com os dados meteorológicos que ela anexou, a versão em inglês do modelo está dando este alerta:
![imagem2](https://cloud.githubusercontent.com/assets/16117157/12832849/e32554da-cb83-11e5-928c-5bc447421b02.jpg)

OBS: desconsiderem o ponto de exclamação, ele se refere a outra rodada
