### ISSUE TITLE
Ajustes a serem realizados no Programa

### ISSUE THREAD

**Issue by LilianUhlmann** [RomuloPBenedetti/PhenoGlad#29]
- [x] No arquivo de entrada dos dados meteorológicos **(na versão em inglês do programa)** ajustar para que o cabeçalho fique: Year / Doy / Tmin / TMax;

- [x] Idem para o cabeçalho do arquivo .txt de saída, que deve ser: Day / Year / TMin / TMax / TMed / fTMed / DVS / CLN / V_Stage;

- [x] O programa está dando erro no arquivo .txt de entrada dos dados meteorológicos quando não há erro nos mesmos. Isso acontece principalmente quando uma arquivo de dados meteorológicos foi selecionado pela 2° vez;
- Exemplo de dados de entrada:

[DadosCurInmet.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/174507/DadosCurInmet.txt)

- [x] Ao realizar uma simulação multi-anos, às vezes o programa pula alguns anos e não mostra a resposta para os mesmos na interface. No arquivo resposta detalhado, é gerado um arquivo .txt para todos os anos;

**Comment by camilacbecker** [comment]
Fiz uma simulação com os dados meteorológicos abaixo e com os seguintes dados de entrada:

plantio: 23/06/1961, nº de anos: 55, ciclo tardio, até o ponto de colheita. 
Nos resultados faltou o ano 2003.

plantio: 02/07/1961, nº de anos: 55, ciclo tardio, até o ponto de colheita.
Nos resultados faltou o ano 1989.
[bage rodadas.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/174501/bage.rodadas.txt)
