### ISSUE TITLE
Modificações no arquivo logfile

### ISSUE THREAD

**Issue by camilacbecker** [RomuloPBenedetti/PhenoGlad#31]
**1)** No cabeçalho do arquivo "logfile" colocar as informações utilizadas para a simulação, por exemplo:

PL(01-jun-1961)TARDIO_R2_55

pode ser o mesmo formato de nome das pastinhas de resultados da pasta "results".

**2)**Adicionar no arquivo "logfile" os alertas de danos, por exemplo:

1962: morte da espiga por geada. Dia do Ano 250, 7 de set de 2006, DVS:0.669 (pode ser as mesmas informações que aparecem na interface quando ocorre dano).

**3)**Aparecer no cmd o nome do arquivo de dados meteorológicos que foi inserido no modelo.

**Comment by RomuloPBenedetti** [comment]
This issue was moved to RomuloPBenedetti/CropModelsUFSM#1

**Comment by RomuloPBenedetti** [comment]
This issue was moved to RomuloPBenedetti/CropModelsUFSM#2
