### ISSUE TITLE
danos no arquivo logfile

### ISSUE THREAD

**Issue by camilacbecker** [RomuloPBenedetti/PhenoGlad#32]
1) Gostaríamos que aparecesse o alerta de danos no arquivo logfile apenas até o estágio R2 (ponto de colheita), conforme já havíamos conversado Rômulo.

2) As vezes aparece alguns "warning" no arquivo logfile, como no arquivo abaixo, em que o warning ocorreu logo após a data de plantio 11/07.
Como já havíamos conversado, eu rodei de novo com os mesmos dados e a mesma data de plantio e o warning não apareceu, ou seja, ocorre de forma aleatória. Minha preocupação é se esse erro pode afetar o resultado da simulação.

[29,38_50,38 precoce.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/372713/29.38_50.38.precoce.txt)

dados de entrada utilizados nas simulações:
[29,88_50,38.txt](https://github.com/RomuloPBenedetti/PhenoGlad/files/372721/29.88_50.38.txt)

**Comment by RomuloPBenedetti** [comment]
este repositório é considerado descontinuado, por favor abrir o issue em [CropModelsUFSM](https://github.com/RomuloPBenedetti/CropModelsUFSM)
