### ISSUE TITLE
Definir o cabeçalho dos arquivos de entrada e saída

### ISSUE THREAD

**Issue by RomuloPBenedetti** [RomuloPBenedetti/PhenoGlad#5]
O cabeçalho de saída deve ser:
 **Dia Ano TMin TMax TMed FTMed DVS CLN V-Stage**
O cabeçalho de entrada deve ser:
 **Ano Dia TMin TMax**

**Comment by LilianUhlmann** [comment]
**O cabeçalho do arquivo de entrada deve ser:**

  * Ano    Dia    TMin    TMax

**O cabeçalho do arquivo de saída deve ser:**

  * Dia      Ano      TMin      TMax      TMed      FTMed      DVS      CLN      V_Stage

Assim sendo, a **ordem das variáveis no arquivo de saída será:**
  * day(i)      year(i)      tmin(i)     tmax(i)      tmed(i)      fTmed(i)      DVS(i)     CLN(i)      vStage(i)
